### ISSUE TITLE
The client lacks sufficient authorization 

### ISSUE THREAD

**Issue by gitbenb** [YunoHost-Apps/letsencrypt_ynh#2]
This log is from the install log : 

Failed authorization procedure. me.1-m.cc (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid re$

IMPORTANT NOTES:
- The following errors were reported by the server:
  
  Domain: me.1-m.cc
  Type:   unauthorized
  Detail: Invalid response from
  http://me.1-m.cc/.well-known/acme-challenge/

and this part here is from the terminal install screen : 

 domains='me.1-m.cc '
- installdir=/opt/yunohost/letsencrypt/
- backupFolder=/root/.letsencrypt-backupDuringUninstall
- sudo mkdir /root/.letsencrypt-backupDuringUninstall
- sudo rm -rf /opt/yunohost/letsencrypt/
- sudo rm /etc/cron.weekly/certificateRenewer

Attention : rm: impossible de supprimer « /etc/cron.weekly/certificateRenewer »: Aucun fichier ou dossier de ce type
- sudo mv /etc/letsencrypt /root/.letsencrypt-backupDuringUninstall/etc_letsencrypt
- certPath=/etc/yunohost/certs/
- for domain in '$domains'
- sudo mv /etc/nginx/conf.d/me.1-m.cc.d/000-letsencrypt.conf /root/.letsencrypt-backupDuringUninstall/me.1-m.cc.nginx
- '[' -d /etc/yunohost/certs//me.1-m.cc.beforeLetsEncrypt ']'
- sudo service nginx restart
- sudo service metronome restart

Erreur : Échec de l'installation

**Comment by gitbenb** [comment]
Full log here : https://me.1-m.cc/zerobin/?03c6ca2ff6fdad62#/KfPBAFS48E3qhBKg0lVVYQ2B9TVB6/2eH+/PTq7YjM=

**Comment by buzzworkers** [comment]
I have tried several things to make sure my dns/IP is all setup but I keep having : 

Failed authorization procedure. me.1-m.cc (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://me.1-m.cc/$well-known/acme-challenge/

**Comment by gitbenb** [comment]
This issue can be fixed following these steps : https://1-m.cc/2016/how-to-get-letsencrypt-to-work-with-current-yunohost-version
